# Generated by Django 3.1.1 on 2020-11-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('code', models.TextField(max_length=3)),
                ('min_price', models.IntegerField()),
                ('ref_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('min_bought_price', models.IntegerField()),
                ('max_bought_price', models.IntegerField()),
                ('open_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.TextField(max_length=10)),
                ('code', models.TextField(max_length=3)),
                ('name', models.TextField()),
                ('cafef_link', models.TextField()),
                ('website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('code', models.TextField(max_length=3)),
                ('volume', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=3)),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('code', models.TextField(max_length=3)),
                ('volume', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='testData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('min_order', models.IntegerField()),
                ('max_order', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('change_limit', models.FloatField()),
            ],
        ),
    ]
