# Generated by Django 3.1.1 on 2020-10-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharestockdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='vietstock_link',
        ),
    ]
