# Generated by Django 3.1.1 on 2020-11-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestockdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdaydata',
            name='max_bought_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdaydata',
            name='max_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdaydata',
            name='min_bought_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdaydata',
            name='min_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdaydata',
            name='open_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdaydata',
            name='ref_price',
            field=models.FloatField(),
        ),
    ]
