# Generated by Django 3.1.1 on 2020-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestockdata', '0002_auto_20201109_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='volume',
            field=models.IntegerField(default=100),
        ),
    ]
