# Generated by Django 3.1.1 on 2020-10-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestockdata', '0002_remove_stockinfo_vietstock_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('code', models.TextField(max_length=3)),
                ('volume', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='stockdaydata',
            name='open_price',
            field=models.IntegerField(default=0),
        ),
    ]
