# Generated by Django 3.1.1 on 2020-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestockdata', '0003_auto_20201110_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdaydata',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
