# Generated by Django 3.1.1 on 2020-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestockdata', '0003_auto_20201018_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='testData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('min_order', models.IntegerField()),
                ('max_order', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('change_limit', models.FloatField()),
            ],
        ),
    ]
